blank_issues_enabled: false
contact_links:
- name: Discord
  url: https://discord.gg/9NTWu9MEGq
  about: Chat with CIL developers & users
- name: Docs
  url: https://tomographicimaging.github.io/CIL
  about: CIL documentation website
- name: Pull Request
  url: https://github.com/TomographicImaging/CIL/compare/master?expand=1
  about: Open a pull request
- name: Dev PR
  url: https://github.com/TomographicImaging/CIL/compare/master?template=developers.md
  about: please append `?template=developers.md` to the URL before submitting
